# .goreleaser.yaml
version: 2
project_name: qernal-cli

before:
  hooks:
    - go mod download

builds:
  - id: "cli-windows"
    main: ./cmd/main.go
    binary: qernal
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
  - id: "cli-linux"
    main: ./cmd/main.go
    binary: qernal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
  - id: "cli-macos"
    main: ./cmd/main.go
    binary: qernal
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  mode: append

notarize:
  macos:
    - enabled: "{{ isEnvSet \"MACOS_SIGN_P12\" }}"
      ids:
        - cli-macos-universal
        - cli-macos
      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{ .Env.MACOS_SIGN_PASSWORD }}"

      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"
        wait: true
        timeout: 50m

universal_binaries:
  - id: cli-macos-universal
    replace: true
    ids:
      - cli-macos

archives:
  - id: cli-all-binaries
    formats: ["binary"]
  - id: homebrew-macos-universal
    ids:
      - cli-macos-universal
    formats: ["zip"]
  - id: homebrew-linux
    ids:
      - cli-linux-zips
    formats: ["zip"]

brews:
  - name: qernal
    homepage: 'https://qernal.com/'
    description: 'A CLI tool for Qernal'

    url_template: "https://github.com/qernal/homebrew-qernal/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    ids:
      - homebrew-macos-universal
      - homebrew-linux

    repository:
      owner: qernal
      name: homebrew-qernal
      branch: "{{.ProjectName}}-{{.Version}}"
      token: "{{ .Env.GH_BREW_TOKEN }}"

      pull_request:
        enabled: true
        draft: false

        base:
          branch: main

    commit_author:
      name: "{{ .Env.GIT_AUTHOR_NAME }}"
      email: "{{ .Env.GIT_AUTHOR_EMAIL }}"

    commit_msg_template: "chore: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
