name: qernal-ci

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # validate commits
  commit:
    if: '! github.event.pull_request.draft'
    uses: ./.github/workflows/conventional-commits.yaml
    with:
      lint_only: true

  # run go tests
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run tests
        env:
          # TODO: switch from the build environment
          QERNAL_HOST_CHAOS: https://chaos.bld2.qernal-bld.dev
          QERNAL_HOST_HYDRA: https://hydra.bld2.qernal-bld.dev
          QERNAL_TOKEN: ${{ secrets.QERNAL_CI_TOKEN }}
        run: |
          for dir in $(go list ./commands/...); do
            go test -v $dir
          done